package db

import "errors"

var (
	ErrMissingAutoGeneratedKey = errors.New("Cannot reconstruct auto generated key. Make sure you set the entity's key before applying any of the following operations: Update, Delete or Load")
	ErrMultipleIdFields        = errors.New(`Model marked with multiple db:"id" tags. Make sure you have either a int field or a string field tagged with db:"id"`)
	ErrMissingParentKey        = errors.New(`Model marked with db:",has_parent" is missing parent key. Make sure you set it before attempting any datastore operation on the entity`)
	ErrMissingStringId         = errors.New(`Entity is missing StringId. String field tagged with db:"id" cannot be empty`)
	ErrMissingIntId            = errors.New(`Entity is missing IntId. Integer field tagged with db:"id" cannot be zero`)
	ErrInvalidType             = errors.New("Invalid Type. Expected either a slice or a pointer to a slice")
)
