package db_test

import (
	"github.com/drborges/datastore-model"
	"github.com/drborges/goexpect"
	"testing"
	"appengine/datastore"
	"appengine/aetest"
)

func TestKeyResolverExtractMetadataDefaults(t *testing.T) {
	type Person struct {
		db.Model
		Name     string
		Country  string
	}

	person := new(Person)
	person.Name = "Borges"

	resolver := db.NewKeyResolver(nil)
	err := resolver.ExtractMetadataFrom(person)

	expect := goexpect.New(t)
	expect(err).ToBe(nil)
	expect(resolver.Kind).ToBe("Person")
	expect(resolver.StringID).ToBe("")
	expect(resolver.IntID).ToBe(int64(0))
	expect(resolver.HasParent).ToBe(false)
	expect(resolver.IsAutoGenerated()).ToBe(true)
	expect(resolver.Parent).ToBe((*datastore.Key)(nil))
}

func TestKeyResolverExtractMetadataFromEntityWithStringId(t *testing.T) {
	type Person struct {
		db.Model        `db:"People"`
		Name     string `db:"id"`
		Country  string
	}

	person := new(Person)
	person.Name = "Borges"

	resolver := db.NewKeyResolver(nil)
	err := resolver.ExtractMetadataFrom(person)

	expect := goexpect.New(t)
	expect(err).ToBe(nil)
	expect(resolver.Kind).ToBe("People")
	expect(resolver.IntID).ToBe(int64(0))
	expect(resolver.HasParent).ToBe(false)
	expect(resolver.StringID).ToBe("Borges")
	expect(resolver.IsAutoGenerated()).ToBe(false)
	expect(resolver.Parent).ToBe((*datastore.Key)(nil))
}

func TestKeyResolverExtractMetadataFromEntityWithMissingStringId(t *testing.T) {
	type Person struct {
		db.Model        `db:"People"`
		Name     string `db:"id"`
		Country  string
	}

	err := db.NewKeyResolver(nil).ExtractMetadataFrom(new(Person))

	expect := goexpect.New(t)
	expect(err).ToBe(db.ErrMissingStringId)
}

func TestKeyResolverExtractMetadataFromEntityWithIntId(t *testing.T) {
	type CreditCard struct {
		db.Model   `db:"CreditCards"`
		Number int `db:"id"`
		Owner  string
	}

	card := new(CreditCard)
	card.Number = 123123

	resolver := db.NewKeyResolver(nil)
	err := resolver.ExtractMetadataFrom(card)

	expect := goexpect.New(t)
	expect(err).ToBe(nil)
	expect(resolver.Kind).ToBe("CreditCards")
	expect(resolver.StringID).ToBe("")
	expect(resolver.HasParent).ToBe(false)
	expect(resolver.IntID).ToBe(int64(123123))
	expect(resolver.IsAutoGenerated()).ToBe(false)
	expect(resolver.Parent).ToBe((*datastore.Key)(nil))
}

func TestKeyResolverExtractMetadataFromEntityWithMissingIntId(t *testing.T) {
	type CreditCard struct {
		db.Model   `db:"CreditCards"`
		Number int `db:"id"`
		Owner  string
	}

	err := db.NewKeyResolver(nil).ExtractMetadataFrom(new(CreditCard))

	expect := goexpect.New(t)
	expect(err).ToBe(db.ErrMissingIntId)
}

func TestKeyResolverExtractMetadataFromEntityWithMultipleIdTags(t *testing.T) {
	type CreditCard struct {
		db.Model
		Number int    `db:"id"`
		Owner  string `db:"id"`
	}

	card := new(CreditCard)
	card.Number = 123123
	card.Owner = "Borges"

	resolver := db.NewKeyResolver(nil)
	err := resolver.ExtractMetadataFrom(card)

	expect := goexpect.New(t)
	expect(err).ToBe(nil)
	expect(resolver.Kind).ToBe("CreditCard")
	expect(resolver.StringID).ToBe("")
	expect(resolver.HasParent).ToBe(false)
	expect(resolver.IntID).ToBe(int64(123123))
	expect(resolver.IsAutoGenerated()).ToBe(false)
	expect(resolver.Parent).ToBe((*datastore.Key)(nil))
}

func TestKeyResolverExtractMetadataFromEntityWithParentKey(t *testing.T) {
	c, _ := aetest.NewContext(nil)
	defer c.Close()

	type CreditCard struct {
		db.Model      `db:",hasparent"`
		Number int    `db:"id"`
		Owner  string
	}

	parentKey := datastore.NewIncompleteKey(c, "Parent", nil)
	card := new(CreditCard)
	card.Number = 123123
	card.SetParent(parentKey)

	resolver := db.NewKeyResolver(nil)
	err := resolver.ExtractMetadataFrom(card)

	expect := goexpect.New(t)
	expect(err).ToBe(nil)
	expect(resolver.HasParent).ToBe(true)
	expect(resolver.Parent).ToBe(parentKey)
}

func TestKeyResolverExtractMetadataFromEntityWithMissingParentKey(t *testing.T) {
	type CreditCard struct {
		db.Model      `db:",hasparent"`
		Number int    `db:"id"`
		Owner  string
	}

	card := new(CreditCard)
	card.Number = 123123

	resolver := db.NewKeyResolver(nil)
	err := resolver.ExtractMetadataFrom(card)

	expect := goexpect.New(t)
	expect(err).ToBe(db.ErrMissingParentKey)
	expect(resolver.HasParent).ToBe(true)
	expect(resolver.Parent).ToBe((*datastore.Key)(nil))
}

func TestKeyResolverResolve(t *testing.T) {
	c, _ := aetest.NewContext(nil)
	defer c.Close()

	type CreditCard struct {
		db.Model      `db:",hasparent"`
		Number int    `db:"id"`
		Owner  string
	}

	parentKey := datastore.NewKey(c, "People", "Borges", 0, nil)
	card := new(CreditCard)
	card.Number = 123123
	card.SetParent(parentKey)

	err := db.NewKeyResolver(c).Resolve(card)

	expect := goexpect.New(t)
	expect(err).ToBe(nil)
	expect(card.Key().String()).ToBe("/People,Borges/CreditCard,123123")
}

