package db

import (
	"appengine/datastore"
	"reflect"
)

type Metadata struct {
	Kind      string
	StringID string
	IntID    int64
	HasParent bool
	Parent   *datastore.Key
}

// IsAutoGenerated tells whether or not a resolved key
// is auto generated by datastore
//
// Keys are auto generated if no struct field is tagged with db:"id"
func (this *Metadata) IsAutoGenerated() bool {
	return this.IntID == 0 && this.StringID == ""
}

type MetadataExtractor interface {
	Accept(reflect.StructField) bool
	Extract(entity, reflect.StructField, reflect.Value) error
}